In [ ]:
### 3 3DFs ---> sql server (3 tables Bronze)

In [ ]:

##df_customers
##df_orders
##df_products

In [5]:
import pandas as pd
import xml.etree.ElementTree as ET

In [6]:
##pip install pyodbc
##pip install sqlalchemy

In [1]:
from sqlalchemy import create_engine

engine = create_engine(
    "mssql+pyodbc://DESKTOP-2A0QBS7\SQLEXPRESS/project1_DWH"
    "?trusted_connection=yes"
    "&driver=ODBC+Driver+17+for+SQL+Server"
    "&TrustServerCertificate=yes"
)

In [2]:
import pandas as pd

df_customers = pd.read_csv('./Bronze/customers.csv')

df_customers.head()

   customer_id first_name last_name                    email        city
0            1      Ahmed       Ali          ahmed@gmail.com       Cairo
1            2    Mohamed    Hassan        mohamed@gmail.com        Giza
2            3       Omar   Mahmoud           omar@gmail.com  Alexandria
3            4       Sara   Ibrahim   sara.ibrahim@gmail.com       Luxor
4            5    Youssef     Nabil  youssef.nabil@yahoo.com       Aswan

In [3]:
import pandas as pd

df_orders = pd.read_csv('./Bronze/orders.csv')

df_orders.head()

   order_id  customer_id  product_id  quantity  order_date
0      1001            1         101         1  2026-09-01
1      1002            2         102         2  2026-09-02
2      1003            1         103         1  2026-09-03
3      1004            3         104         3  2026-09-04
4      1005            4         105         2  2026-09-05

In [4]:
import pandas as pd

df_products = pd.read_csv('./Bronze/products.csv')

df_products.head()

   product_id    product_name     category     brand   price
0         101       iPhone 15  Electronics     Apple  799.99
1         102      Galaxy S24  Electronics   Samsung  699.99
2         103    Nike Air Max        Shoes      Nike  129.99
3         104       Air Fryer         Home   Philips  149.99
4         105  Wireless Mouse  Electronics  Logitech   25.50

In [13]:

##df_customers
##df_orders
##df_products

In [7]:
df_customers.to_sql(
    'customers', 
    con=engine,
    schema='bronze',
    if_exists='append', 
    index=False
    )

c:\anaconda3\Lib\site-packages\pandas\io\sql.py:1648: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

50

In [8]:
df_products.to_sql(
    'products', 
    con=engine,
    schema='bronze',
    if_exists='append', 
    index=False
    )

10

In [9]:
df_orders.to_sql(
    'orders', 
    con=engine,
    schema='bronze',
    if_exists='append', 
    index=False
    )

30